# Telegram Bot Settings
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHANNEL_ID = "@YOUR_CHANNEL_USERNAME"

# DeepSeek API Settings
DEEPSEEK_API_KEY = "YOUR_DEEPSEEK_API_KEY"
DEEPSEEK_API_BASE_URL = "https://api.deepseek.com"
